openapi: 3.0.0
info:
  title: Sample API
  description: This is sample API
  version: 0.0.1
servers:
  - url: http://localhost:10080
    description: local dev server
  - url: http://localhost:4010
    description: local mock on docker by prism
  - url: http://localhost:5000
    description: local mock by connexion
paths:
  /users:
    $ref: "components/paths/users.yml"
  /pets:
    $ref: "components/paths/pets.yml"
